// <auto-generated />
using System;
using IndustrialMonitorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndustrialMonitorAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912071739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("IndustrialMonitorAPI.Models.AlarmRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlarmLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecoverTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AlarmRecords");
                });

            modelBuilder.Entity("IndustrialMonitorAPI.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<float>("InitialPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("InitialRpm")
                        .HasColumnType("INTEGER");

                    b.Property<float>("InitialRuntime")
                        .HasColumnType("REAL");

                    b.Property<float>("InitialTemperature")
                        .HasColumnType("REAL");

                    b.Property<float>("Pressure")
                        .HasColumnType("REAL");

                    b.Property<int>("Rpm")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Runtime")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Workshop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceName = "设备 A",
                            DeviceType = "生产设备",
                            InitialPressure = 1.62f,
                            InitialRpm = 1450,
                            InitialRuntime = 128.5f,
                            InitialTemperature = 65.2f,
                            Pressure = 1.62f,
                            Rpm = 1450,
                            Runtime = 128.5f,
                            Status = "正常",
                            Temperature = 65.2f,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Workshop = "一号车间"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceName = "设备 B",
                            DeviceType = "生产设备",
                            InitialPressure = 1.7f,
                            InitialRpm = 1500,
                            InitialRuntime = 96.3f,
                            InitialTemperature = 68.5f,
                            Pressure = 1.7f,
                            Rpm = 1500,
                            Runtime = 96.3f,
                            Status = "正常",
                            Temperature = 68.5f,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Workshop = "一号车间"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceName = "设备 C",
                            DeviceType = "生产设备",
                            InitialPressure = 1.55f,
                            InitialRpm = 1380,
                            InitialRuntime = 210.7f,
                            InitialTemperature = 61.8f,
                            Pressure = 1.55f,
                            Rpm = 1380,
                            Runtime = 210.7f,
                            Status = "正常",
                            Temperature = 61.8f,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Workshop = "二号车间"
                        });
                });

            modelBuilder.Entity("IndustrialMonitorAPI.Models.DeviceMetricHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeviceName", "MetricName", "Timestamp");

                    b.ToTable("DeviceMetricHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
